name: Sync Gitee Develop Branch

on:
  schedule:
    - cron: '0 2 * * *'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          ref: 'develop'

      - name: Sync from Gitee Repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          echo 'Adding Gitee remote...'
          git remote add gitee https://gitee.com/RobinNotBad/BiliClient.git
          
          echo 'Fetching from Gitee develop branch...'
          git fetch gitee develop
          
          echo 'Resetting local develop to Gitees develop...'
          git reset --hard gitee/develop
          
          echo 'Force pushing to GitHub develop branch...'
          git push origin develop --force
          
          echo 'Sync completed.'
